spring:
  data:
    mongodb:
        host: localhost
        port: 27017
        database: mainMongoDb

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

#logging:
#  level:
#    root: ERROR

server:
  port: 8090
