server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
  servlet:
    context-path:
  port: 8090

spring:
  sql:
    init:
      mode: always

  datasource:
    # Эти свойства будут перегружены свойствами в docker-compose.yml
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        enable_lazy_load_no_trans=true:
        format_sql: true
        use_sql_comments: true

    show-sql: true