server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
  servlet:
    context-path:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:maindb
#    url: jdbc:h2:file:~/maindb;AUTO_SERVER=TRUE;OLD_INFORMATION_SCHEMA=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
        enable_lazy_load_no_trans=true:
#        format_sql: true
        use_sql_comments: true

    show-sql: true