server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
  servlet:
    context-path:
  port: 8090

spring:
  application:
    name: library-server
  sql:
    init:
      mode: always
      data-locations: "classpath:data.sql"
      schema-locations: "classpath:schema.sql"

  datasource:
    # Эти свойства будут перегружены свойствами в docker-compose.yml
    url: jdbc:postgresql://localhost:5430/db
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: create

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true