spring:
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:h2:mem:maindb
#    url: jdbc:h2:file:~/maindb;AUTO_SERVER=TRUE;OLD_INFORMATION_SCHEMA=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect